name: Deploy Supabase Functions

on:
  push:
    branches: [main]
    paths:
      - 'supabase/functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Supabase CLI
        run: npm install -g supabase
      - name: Deploy Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ajkjsezdaulybvrscoyv
        run: |
          supabase login --token "$SUPABASE_ACCESS_TOKEN"
          supabase functions deploy premiumize-proxy --project-ref "$SUPABASE_PROJECT_ID"