name: Deploy Supabase Functions

on:
  push:
    branches: [main]
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:  # Optional: allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest  # Or a specific version, e.g., 1.187.2
      - name: Deploy Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ajkjsezdaulybvrscoyv
        run: |
          supabase login --token "$SUPABASE_ACCESS_TOKEN"
          supabase functions deploy premiumize-proxy --project-ref "$SUPABASE_PROJECT_ID"